### ISSUE TITLE
Error on media stream videotracks on IOS build

### ISSUE THREAD

**Issue by DustinnBel** [OpenVidu/openvidu#490]
First of all, the application is working perfectly in the browser.

But when I run this:
- ionic cordova prepare iOS

Then start the Xcode project from the iOS folder in platforms, click on the play button and it launches. But as it want to lists the audio and video devices I get the following error: 

2020-05-23 17:33:28.938315+0200 test[7425:7008108] PluginRTCVideoCaptureController#findDevice deviceFrameRate:15
2020-05-23 17:33:28.938599+0200 test[7425:7008108] PluginRTCVideoCaptureController#startCapture Capture started, device:<AVCaptureFigVideoDevice: 0x135f26130 [Front Camera][com.apple.avfoundation.avcapturedevice.built-in_video:1]>, format:<AVCaptureDeviceFormat: 0x281100b80 'vide'/'420v'  640x 480, { 1- 60 fps}, HRSI:1624x1218, fov:53.957, binned, max zoom:76.12 (upscales @2.54), ISO:18.0-1728.0, SS:0.000020-1.000000, supports multicam>
2020-05-23 17:33:28.938689+0200 test[7425:7008108] PluginGetUserMedia#call() | audio requested
2020-05-23 17:33:28.938889+0200 test[7425:7008108] PluginGetUserMedia#call() | chosen audio constraints: {
}
2020-05-23 17:33:28.939781+0200 test[7425:7008108] PluginMediaStream#init()
2020-05-23 17:33:28.939876+0200 test[7425:7008108] PluginMediaStreamTrack#init()
2020-05-23 17:33:28.939948+0200 test[7425:7008108] PluginMediaStreamTrack#run() [kind:audio, id:87BC7C59-F0FD-4102-82BC-D0D5FD09624F_5F8AD419-77EC-40BB-B1E8-CBB7A88B2A18]
2020-05-23 17:33:28.940006+0200 test[7425:7008108] PluginMediaStreamTrack#init()
2020-05-23 17:33:28.940063+0200 test[7425:7008108] PluginMediaStreamTrack#run() [kind:video, id:1DF521E6-E340-4188-91F6-448D3C9617CF_BBB24C3E-11A1-4317-959C-6B892C61FB8E]
2020-05-23 17:33:28.940087+0200 test[7425:7008108] PluginMediaStream#run()
2020-05-23 17:33:28.940340+0200 test[7425:7008108] THREAD WARNING: ['iosrtcPlugin'] took '30.092041' ms. Plugin should use a background thread.
2020-05-23 17:33:28.943006+0200 test[7425:7008108] iosrtcPlugin#MediaStream_setListener()
2020-05-23 17:33:28.943136+0200 test[7425:7008337] PluginMediaStream#setListener()
2020-05-23 17:33:28.945157+0200 test[7425:7008108] iosrtcPlugin#MediaStreamTrack_setListener()
2020-05-23 17:33:28.945280+0200 test[7425:7008108] iosrtcPlugin#MediaStreamTrack_setListener()
2020-05-23 17:33:28.945297+0200 test[7425:7008337] PluginMediaStreamTrack#setListener() [kind:audio, id:87BC7C59-F0FD-4102-82BC-D0D5FD09624F_5F8AD419-77EC-40BB-B1E8-CBB7A88B2A18]
2020-05-23 17:33:28.945365+0200 test[7425:7008337] PluginMediaStreamTrack#setListener() [kind:video, id:1DF521E6-E340-4188-91F6-448D3C9617CF_BBB24C3E-11A1-4317-959C-6B892C61FB8E]
2020-05-23 17:33:28.947253+0200 test[7425:7008108] iosrtcPlugin#MediaStreamTrack_setEnabled()
2020-05-23 17:33:28.947380+0200 test[7425:7008108] iosrtcPlugin#MediaStreamTrack_setEnabled()
2020-05-23 17:33:28.947406+0200 test[7425:7008337] PluginMediaStreamTrack#setEnabled() [kind:audio, id:87BC7C59-F0FD-4102-82BC-D0D5FD09624F_5F8AD419-77EC-40BB-B1E8-CBB7A88B2A18, value:true]
2020-05-23 17:33:28.947512+0200 test[7425:7008337] PluginMediaStreamTrack#setEnabled() [kind:video, id:1DF521E6-E340-4188-91F6-448D3C9617CF_BBB24C3E-11A1-4317-959C-6B892C61FB8E, value:true]
2020-05-23 17:33:29.106234+0200 test r[7425:7008108] ERROR: {}
2020-05-23 17:33:29.107188+0200 test[7425:7008108] {"name":"GENERIC_ERROR","message":"TypeError: mediaStream.getVideoTracks()[0].getSettings is not a function. (In 'mediaStream.getVideoTracks()[0].getSettings()', 'mediaStream.getVideoTracks()[0].getSettings' is undefined)"}

This is the code from the example project. Am I building the project wrong or?

And when I just click on join with the error I get the following:
2020-05-23 17:42:58.589055+0200 Test[7425:7008108] ERROR: There was an error connecting to the session:  Browser null (version null) for OS X is not supported in OpenVidu.

Its saying something about OS X while it is running on my iPad.

A new update:
The same application is running perfect on a iPhone X with iOS 13.4.1.
It is giving me the errors above on an iPad Pro 2020 with iOS 13.4.1
It works on an iPad Air with IOS 12.4.5

**Comment by anupzone** [comment]
checked in ipad app which is using safari 14, issue still there. I found in code platform.js for detecting browsers and apps which is supporting till safari 13 and that's why giving browser null in return. posted issue here also:
[https://openvidu.discourse.group/t/ipad-pro-still-giving-same-error-in-2-15-0-version/2140](url)
